#!/usr/bin/env python3
"""build_calor.py — Calor do Dia (reporte interno de gestão APW) · v1 (ago/2026)
Uso: python3 build_calor.py calor_<ALVO>.json <saida>
Gera: PNG (resumo executivo, colável no e-mail) + PDF (completo, com histórico) + 2 HTML.

Entradas: JSON produzido por collect_calor.js (deals que moveram no dia + histórico
completo de atividades + atividades concluídas no dia pelos 13 diretores).

Seções: (1) painel; (2) CALOR — deals avançando (score por sinais); (3) qualificações
com BANDEIRA de torreira/trava; (4) situação de cada deal (última nota do dono atual);
(5) HISTÓRICO COMPLETO — todas as atividades com conteúdo, cronológico, texto integral.

Identidade: apw-brand (Navy #012B5E, Azul #1C75BB, Sage #91A5A4, Verde #009877, Oliva #A7AF00)."""
import sys, json, os, re, html, datetime

NAVY="#012B5E";AZUL="#1C75BB";SAGE="#91A5A4";VERDE="#009877";OLIVA="#A7AF00"
RED="#C0392B";CINZA="#5D5D5D";AMBAR="#E8A33D"

# padroes que indicam atividade AUTOMATICA (busca no texto INTEIRO, nao so no inicio)
AUTO_ANY=[r"mail\s*merge",r"this is an automatic activity",r"automatic activity generated",
          r"template using the",r"response generated by",r"created the .*template"]
# padroes que indicam atividade automatica quando aparecem no INICIO do texto
AUTO_START=[r"^\s*$",r"^(please\s+)?begin work",r"^assigned",r"^management task",
            r"moved to stage",r"^opportunity .*(created|updated|reassigned)",
            r"^lead .*(created|qualified|disqualified)",r"^workflow",r"^reminder:",
            r"notifica[çc][ãa]o autom[áa]tica",r"^atividade gerada pelo sistema",
            r"^follow-?up: begin work"]
def is_auto(t):
    t=(t or "").strip()
    if not t: return True
    if any(re.search(rx,t,re.I) for rx in AUTO_ANY): return True
    return any(re.search(rx,t[:90],re.I) for rx in AUTO_START)

SIN=[r"\b(r\$|\d{1,3}(\.\d{3})+(,\d{2})?)",r"\b(s[íi]ndico|propriet[áa]rio|administradora|condom[íi]nio|operadora|torre|locador|advogad)",
     r"\b(pr[óo]ximo passo|retornar|agendar|enviar|aguard|follow|reuni[ãa]o|visita|proposta|marcar|ligar)",
     r"\b(objec|objeç|recus|negociaç|contraproposta|exig|condiç|quer|pediu|preocupa)"]
# sinais de avanço real (exige pelo menos 1 para não ser descartada por frustração)
SIN_AVAN=[r"\b(proposta|contraproposta|aceit|fechou|assinatu|negociaç|interesse|interessad|receptiv|retornou|respondeu|reunião|visita|enviado|confirmou|agendou|falamos|conversei|contrato|aluguel|valor|r\$)",]
# padrões de tentativa frustrada que inflam char sem conteúdo estratégico
FRUSTRA=re.compile(r"(n[ãa]o atende|nao atende|liga[çc][ãa]o n[ãa]o atendida|sem retorno|n[ãa]o respondeu|n[ãa]o atendeu|caixa postal|tentativa|aguardando retorno|sem sucesso|liguei e n[ãa]o|mandei mensagem|mandei whatsapp|enviei mensagem|n[ãa]o consegui falar)",re.I)
def subst(t):
    if not t: return False
    s=t.strip(); L=len(s)
    if L<140: return False
    n_sin=sum(1 for rx in SIN if re.search(rx,s,re.I))
    # texto grande E com sinal de avanço real → substantiva
    tem_avan=any(re.search(rx,s,re.I) for rx in SIN_AVAN)
    # se dominado por frustração E sem sinal de avanço → não é substantiva
    if FRUSTRA.search(s) and not tem_avan: return False
    return L>=180 or (L>=140 and n_sin>=2)

CALOR=[(r"\bAGE\b.*(aprovad|ok)|aprovaç[ãa]o.*AGE","AGE aprovada",3),
       (r"\baceite\b|\bLOI\b|aceitou a proposta|aceitaram","Aceite / LOI",3),
       (r"docusign|assinatur|assinad|assinou","Assinatura",3),
       (r"contraproposta|contra-proposta","Contraproposta",2),
       (r"\bproposta\b.*(enviad|apresent|entregu)|enviei a proposta","Proposta enviada",2),
       (r"R\$\s?\d{1,3}(\.\d{3})+","Valor cheio",1),
       (r"edital|matr[íi]cula|conven[çc][ãa]o","Edital / matrícula",1),
       (r"desconto|majora[çc]|aumento do aluguel","Desconto / majoração",1),
       (r"s[íi]ndico.*(interess|gostou|favor)|propriet[áa]rio.*(interess|gostou)","Contraparte interessada",2)]

FLAGS=[(r"\bIHS\b|\bCSS\b|Centennial","IHS","🟡","IHS/CSS só compra terreno — cessão/DRS não fecha"),
       (r"\bTBSA\b|Torres do Brasil","TBSA","","",),
       (r"\bPTI\b|Phoenix|\bQMC\b","PTI/Phoenix/QMC","🟡","Confirmar cláusula anti-agregador"),
       (r"veda[çc][ãa]o|anti-?cess[ãa]o|anti-?drs|exclusividade telecom","Trava contratual","🔴","Vedação/exclusividade citada no texto")]
COND_RX=r"condom[íi]nio|edif[íi]cio|\bcond\.|residencial|\bed\b|tower"

def esc(t): return html.escape((t or "").strip())
def clean(t):
    t=(t or "")
    t=re.sub(r"<(script|style)[^>]*>.*?</\1>"," ",t,flags=re.S|re.I)   # blocos inteiros
    t=re.sub(r"<br\s*/?>|</p>|</div>|</tr>","  ",t,flags=re.I)          # quebras viram espaco
    t=re.sub(r"<[^>]{0,400}>"," ",t)                                    # demais tags
    t=html.unescape(t)
    t=re.sub(r"https?://[^\s]{60,}"," [link] ",t)                       # URLs gigantes do CRM
    t=re.sub(r"[\r\n\t]+"," ",t); t=re.sub(r"\s{2,}"," ",t)
    return t.strip()

CAP=1400
def cap(t):
    t=clean(t)
    return t if len(t)<=CAP else t[:CAP].rsplit(" ",1)[0]+" […]"

def main():
    c=json.load(open(sys.argv[1])); out=sys.argv[2] if len(sys.argv)>2 else "."
    ALVO=c["alvo"]; dt=datetime.date.fromisoformat(ALVO)
    dows=["segunda","terça","quarta","quinta","sexta","sábado","domingo"]
    deals=c["deals"]; acts=c["acts_dia"]

    # ---- enriquecimento por deal ----
    for d in deals:
        ats=[]
        for a in d["atividades"]:
            body=clean(a.get("desc") or "")
            if is_auto(body) and is_auto(a.get("subject") or ""): continue
            if len(body)<20 and len((a.get("subject") or "").strip())<8: continue
            a["_body"]=body; ats.append(a)
        d["_ats"]=ats
        own=[a for a in ats if a["owner_guid"]==d["dono_guid"]]
        d["_ult"]=own[-1] if own else (ats[-1] if ats else None)
        d["_ult_e_dono"]=bool(own)
        blob=d["nome"]+" "+" ".join((a.get("desc") or "")+" "+(a.get("subject") or "") for a in ats)
        d["_blob"]=blob
        d["_cond"]=bool(re.search(COND_RX,d["nome"],re.I))
        # calor
        sig=[]
        for rx,lab,peso in CALOR:
            if re.search(rx,blob,re.I): sig.append((lab,peso))
        d["_sig"]=sig; d["_calor"]=sum(p for _,p in sig)
        # bandeiras
        fl=[]
        for rx,nome,ic,mot in FLAGS:
            if not re.search(rx,blob,re.I): continue
            if nome=="TBSA":
                if d["_cond"]: fl.append(("🔴","TBSA em condomínio","Cessão travada — não fecha"))
                else: fl.append(("🟡","TBSA fora de condomínio","Rotear via DRS"))
            else: fl.append((ic,nome,mot))
        d["_flags"]=fl
    deals.sort(key=lambda d:(-d["_calor"],d["L"]))

    n_s1=sum(1 for d in deals if "S1" in d["tipos"]); n_s3=sum(1 for d in deals if "S3" in d["tipos"])
    n_rp=sum(1 for d in deals if "REPROP" in d["tipos"])
    a_sub=sum(1 for a in acts if subst(a.get("desc")))
    a_auto=sum(1 for a in acts if is_auto(a.get("desc")) and is_auto(a.get("subject")))
    quentes=[d for d in deals if d["_calor"]>=3]
    bandeiras=[d for d in deals if d["_flags"]]

    SECT=f'font-size:14px;font-weight:bold;color:{NAVY};border-bottom:2px solid {AZUL};padding-bottom:4px;'
    def tipo_chip(t):
        cor={"S1":SAGE,"S3":AZUL,"REPROP":OLIVA}.get(t,CINZA)
        return f'<span style="background:{cor};color:#fff;font-size:9.5px;font-weight:bold;padding:1.5px 5px;border-radius:3px;margin-right:3px;">{t}</span>'

    # ---- CALOR ----
    ch=""
    for d in quentes:
        sg=" · ".join(f"<b>{esc(l)}</b>" for l,_ in sorted(d["_sig"],key=lambda x:-x[1])[:4])
        u=d["_ult"]; txt=clean((u.get("desc") or u.get("subject") or ""))[:400] if u else "— sem atividade com conteúdo —"
        cor=NAVY if d["_ult_e_dono"] else RED
        aut=f'{esc(u["owner"])} · {u["data"]}' if u else ""
        av="" if d["_ult_e_dono"] else " <b>(NÃO é do dono atual)</b>"
        ch+=f"""<tr><td style="padding:9px 10px;border-bottom:1px solid #e6ecf2;vertical-align:top;width:200px;">
<div style="font-size:13px;font-weight:bold;color:{NAVY};">{d['L']}</div>
<div style="font-size:10.5px;color:{CINZA};padding:2px 0;">{esc(d['nome'][:44])}</div>
<div style="padding-top:3px;">{''.join(tipo_chip(t) for t in d['tipos'])}{'<span style="background:'+RED+';color:#fff;font-size:9px;padding:1.5px 5px;border-radius:3px;">POOL</span>' if d['pool'] else ''}</div>
<div style="font-size:11px;color:{NAVY};padding-top:4px;">{esc(d['dono_atual'])}</div></td>
<td style="padding:9px 10px;border-bottom:1px solid #e6ecf2;vertical-align:top;">
<div style="font-size:11.5px;color:{VERDE};padding-bottom:4px;">🔥 {sg} <span style="color:{CINZA}">(score {d['_calor']})</span></div>
<div style="font-size:11.5px;color:{cor};line-height:1.45;">{esc(txt)}</div>
<div style="font-size:10px;color:{cor};padding-top:3px;">— {aut}{av}</div></td></tr>"""
    if not ch: ch=f'<tr><td style="padding:12px;color:{CINZA};font-size:12px;">Nenhum deal com sinal forte de avanço em {dt.strftime("%d/%m")}.</td></tr>'

    # ---- BANDEIRAS ----
    bh=""
    for d in bandeiras:
        fl="<br>".join(f'{i} <b style="color:{NAVY}">{esc(n)}</b> <span style="color:{CINZA};font-size:10.5px">— {esc(m)}</span>' for i,n,m in d["_flags"])
        bh+=f"""<tr><td style="padding:8px 10px;border-bottom:1px solid #e6ecf2;vertical-align:top;width:190px;">
<div style="font-size:12.5px;font-weight:bold;color:{NAVY};">{d['L']} {''.join(tipo_chip(t) for t in d['tipos'])}</div>
<div style="font-size:10.5px;color:{CINZA};">{esc(d['nome'][:42])}</div>
<div style="font-size:10.5px;color:{NAVY};padding-top:2px;">{esc(d['dono_atual'])}</div></td>
<td style="padding:8px 10px;border-bottom:1px solid #e6ecf2;font-size:11.5px;vertical-align:top;">{fl}</td></tr>"""
    if not bh: bh=f'<tr><td style="padding:12px;color:{CINZA};font-size:12px;">Nenhuma bandeira detectada.</td></tr>'

    # ---- SITUAÇÃO DE TODOS OS DEALS ----
    sh=""
    for d in sorted(deals,key=lambda x:x["L"]):
        u=d["_ult"]
        if u:
            txt=clean(u.get("desc") or u.get("subject") or "")[:260]
            cor=NAVY if d["_ult_e_dono"] else RED
            src=f'{esc(u["owner"])} · {u["data"]}'+("" if d["_ult_e_dono"] else " ⚠ ex-dono")
        else:
            txt="— sem atividade com conteúdo no CRM —"; cor=RED; src="—"
        sh+=f"""<tr><td style="padding:7px 9px;border-bottom:1px solid #eef2f6;font-size:12px;color:{NAVY};white-space:nowrap;vertical-align:top;"><b>{d['L']}</b><br>{''.join(tipo_chip(t) for t in d['tipos'])}</td>
<td style="padding:7px 9px;border-bottom:1px solid #eef2f6;font-size:11px;color:{CINZA};vertical-align:top;width:130px;">{esc(d['dono_atual'])}<br><span style="font-size:10px;">{len(d['_ats'])} ativ.</span></td>
<td style="padding:7px 9px;border-bottom:1px solid #eef2f6;font-size:11.5px;color:{cor};line-height:1.4;vertical-align:top;">{esc(txt)}<div style="font-size:9.5px;color:{cor};padding-top:2px;">— {src}</div></td></tr>"""


    # ---- HISTORICO COMPLETO DE ATIVIDADES (todos os deals que moveram) ----
    TIPO_LBL={"task":"Tarefa","phonecall":"Ligação","email":"E-mail","appointment":"Reunião",
              "campaignresponse":"Chat/Campanha","letter":"Carta","fax":"Fax"}
    hh=""
    for d in sorted(deals,key=lambda x:x["L"]):
        ats=sorted(d["_ats"],key=lambda a:(a.get("data") or ""))
        chips="".join(tipo_chip(t) for t in d["tipos"])
        poolc='<span style="background:'+RED+';color:#fff;font-size:9px;padding:1.5px 5px;border-radius:3px;margin-left:3px;">POOL</span>' if d["pool"] else ""
        hh+=f"""<tr><td colspan="2" style="background:{NAVY};padding:8px 11px;">
<span style="font-size:13.5px;font-weight:bold;color:#fff;">{d['L']}</span>
<span style="font-size:11px;color:{SAGE};"> &nbsp;{esc(d['nome'][:60])}</span>{poolc}
<span style="float:right;font-size:11px;color:#fff;">{chips} &nbsp;{esc(d['dono_atual'])} &nbsp;<span style="color:{SAGE}">· {len(ats)} ativ.</span></span></td></tr>"""
        if not ats:
            hh+=f'<tr><td colspan="2" style="padding:8px 11px;border-bottom:1px solid #dce4ec;font-size:11.5px;color:{RED};">— nenhuma atividade com conteúdo no CRM —</td></tr>'
            continue
        for a in ats:
            dono = a["owner_guid"]==d["dono_guid"]
            cor  = NAVY if dono else RED
            bg   = "#ffffff" if dono else "#fdf3f2"
            txt  = cap(a.get("_body") or a.get("subject") or "")
            tp   = TIPO_LBL.get(a.get("tipo",""),a.get("tipo",""))
            sj   = esc(a.get("subject") or "")
            mark = "" if dono else ' <b>⚠ não é o dono atual</b>'
            hh+=f"""<tr style="background:{bg};"><td style="padding:7px 10px;border-bottom:1px solid #eef2f6;vertical-align:top;width:118px;white-space:nowrap;">
<div style="font-size:11px;font-weight:bold;color:{cor};">{a.get('data','')}</div>
<div style="font-size:10px;color:{CINZA};">{esc(tp)}</div>
<div style="font-size:10px;color:{cor};line-height:1.3;">{esc(a.get('owner') or '')}{mark}</div></td>
<td style="padding:7px 10px;border-bottom:1px solid #eef2f6;vertical-align:top;">
<div style="font-size:10.5px;color:{SAGE};font-weight:bold;padding-bottom:2px;">{sj}</div>
<div style="font-size:11.5px;color:{cor};line-height:1.5;word-break:break-word;overflow-wrap:anywhere;">{esc(txt)}</div></td></tr>"""
    if not hh: hh='<tr><td style="padding:12px;">—</td></tr>'

    def doc(HIST):
     HSEC=""
     if HIST:
      HSEC=('<tr><td style="padding:10px 26px 4px;"><div style="'+SECT+'">HISTORICO COMPLETO DE ATIVIDADES &mdash; TODOS OS DEALS QUE MOVERAM</div>'
            '<div style="font-size:10.5px;color:'+CINZA+';padding-top:3px;">Ordem cronologica (mais antiga &rarr; recente), texto integral. '
            'Linhas em <b style="color:'+RED+'">vermelho</b> = atividade escrita por quem <b>nao e o dono atual</b> da opp. '
            'Atividades automaticas removidas.</div></td></tr>'
            '<tr><td style="padding:6px 26px 16px;"><table role="presentation" width="100%" style="border-collapse:collapse;border:1px solid #dce4ec;table-layout:fixed;width:100%;">'+hh+'</table></td></tr>')
     return f"""<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#eef2f6;margin:0;padding:24px 0;"><tr><td align="center">
<table role="presentation" width="960" cellpadding="0" cellspacing="0" style="width:960px;background:#fff;border:1px solid #d6dee6;font-family:Arial,Helvetica,sans-serif;">
<tr><td style="background:{NAVY};padding:18px 26px;"><table role="presentation" width="100%"><tr>
<td align="left" valign="middle"><span style="font-size:26px;font-weight:bold;color:#fff;letter-spacing:1px;">APW</span><span style="font-size:26px;color:{SAGE};letter-spacing:2px;">Brasil</span></td>
<td align="right" valign="middle" style="color:#fff;"><span style="font-size:15px;font-weight:bold;">Calor do Dia — Reporte Interno de Gestão</span><br><span style="color:{SAGE};font-size:12px;">Diretoria de Aquisições · uso interno</span></td></tr></table></td></tr>
<tr><td style="background:{AZUL};height:4px;font-size:0;line-height:4px;">&nbsp;</td></tr>
<tr><td style="padding:16px 26px 6px;"><span style="font-size:18px;font-weight:bold;color:{NAVY};">{dows[dt.weekday()]}, {dt.strftime('%d/%m/%Y')}</span>
<span style="font-size:12.5px;color:{CINZA};">&nbsp;·&nbsp; {len(deals)} deals moveram &nbsp;·&nbsp; {len(acts)} atividades concluídas</span></td></tr>

<tr><td style="padding:6px 26px 12px;"><table role="presentation" width="100%" style="border-collapse:collapse;font-size:12.5px;">
<tr><td style="padding:7px 10px;background:#f4f7fa;border:1px solid #dce4ec;color:{NAVY};width:20%;"><b>Stage 1:</b> {n_s1}</td>
<td style="padding:7px 10px;background:#f4f7fa;border:1px solid #dce4ec;color:{NAVY};width:20%;"><b>Stage 3:</b> {n_s3}</td>
<td style="padding:7px 10px;background:#f4f7fa;border:1px solid #dce4ec;color:{NAVY};width:20%;"><b>Repropostas:</b> {n_rp}</td>
<td style="padding:7px 10px;background:#f4f7fa;border:1px solid #dce4ec;color:{NAVY};width:20%;"><b>Quentes:</b> <span style="color:{VERDE}">{len(quentes)}</span></td>
<td style="padding:7px 10px;background:#f4f7fa;border:1px solid #dce4ec;color:{NAVY};"><b>Bandeiras:</b> <span style="color:{RED}">{len(bandeiras)}</span></td></tr></table></td></tr>

<tr><td style="padding:8px 26px 4px;"><div style="{SECT}">🔥 CALOR — DEALS AVANÇANDO</div></td></tr>
<tr><td style="padding:6px 26px 14px;"><table role="presentation" width="100%" style="border-collapse:collapse;background:#fbfcfe;border:1px solid #dce4ec;">{ch}</table></td></tr>

<tr><td style="padding:8px 26px 4px;"><div style="{SECT}">🚩 QUALIFICAÇÕES COM BANDEIRA</div>
<div style="font-size:10.5px;color:{CINZA};padding-top:3px;">Detecção heurística sobre nome do deal + descrições. <b>Confirmar detentora e trilha no CRM</b> antes de tratar como dead-end.</div></td></tr>
<tr><td style="padding:6px 26px 14px;"><table role="presentation" width="100%" style="border-collapse:collapse;background:#fffdf7;border:1px solid #e6dcc4;">{bh}</table></td></tr>

<tr><td style="padding:8px 26px 4px;"><div style="{SECT}">📋 SITUAÇÃO DE CADA DEAL QUE MOVEU</div>
<div style="font-size:10.5px;color:{CINZA};padding-top:3px;">Última nota do <b>dono atual</b>. Em <b style="color:{RED}">vermelho</b> = nota de outro diretor (ex-dono) ou deal sem nota.</div></td></tr>
<tr><td style="padding:6px 26px 16px;"><table role="presentation" width="100%" style="border-collapse:collapse;border:1px solid #dce4ec;">{sh}</table></td></tr>

{HSEC}
<tr><td style="background:{NAVY};padding:15px 26px;">
<p style="margin:0 0 6px;font-size:12px;color:#fff;"><b>APW</b><span style="color:{SAGE}">Brasil</span> &nbsp;·&nbsp; APWireless Brasil Invest. Imob. LTDA</p>
<p style="margin:0;font-size:10.5px;color:{SAGE};line-height:1.5;">Deals movidos em {dt.strftime('%d/%m')} (S1: lease economics · S3: stage3date · Reprop: pricing createdon ≠ stage3/5). {len(acts)} atividades concluídas no dia pelos 13 diretores ({a_sub} substantivas · {a_auto} automáticas descartadas do conteúdo). Bandeiras por heurística de texto — não substituem checagem da detentora no CRM. Dados via Web API Dynamics 365. <b>Uso interno — não circular fora da Diretoria de Aquisições.</b></p></td></tr>
</table></td></tr></table>"""

    os.makedirs(out,exist_ok=True)
    hp_r=os.path.join(out,f"calor-do-dia-apw-{ALVO}-resumo.html"); open(hp_r,"w").write(doc(False))
    hp_f=os.path.join(out,f"calor-do-dia-apw-{ALVO}-completo.html"); open(hp_f,"w").write(doc(True))
    pp=os.path.join(out,f"calor-do-dia-apw-{ALVO}.png"); pdf=os.path.join(out,f"calor-do-dia-apw-{ALVO}.pdf")
    try:
        from playwright.sync_api import sync_playwright
        with sync_playwright() as p:
            b=p.chromium.launch(executable_path="/opt/google/chrome/chrome",args=["--no-sandbox","--force-color-profile=srgb"])
            pg=b.new_page(viewport={"width":1020,"height":1200},device_scale_factor=2)
            pg.goto("file://"+os.path.abspath(hp_r),wait_until="networkidle"); pg.wait_for_timeout(400)
            pg.screenshot(path=pp,full_page=True); pg.close()
            pg2=b.new_page(viewport={"width":1020,"height":1200})
            pg2.goto("file://"+os.path.abspath(hp_f),wait_until="networkidle"); pg2.wait_for_timeout(600)
            pg2.pdf(path=pdf,format="A4",print_background=True,margin={"top":"9mm","bottom":"9mm","left":"6mm","right":"6mm"})
            b.close()
        print("OK png(resumo):",pp); print("OK pdf(completo):",pdf)
    except Exception as e:
        print("HTML ok, render falhou:",e)

if __name__=="__main__": main()
