#!/usr/bin/env python3
"""audit_atividades.py — Auditoria de atividades concluídas por diretor (apw-atividades-semana v2)

Uso:
  python3 audit_atividades.py <atividades_*.json> <pasta_saida>

Entrada: JSON do collect_semana.js v2 (chaves: janela, atividades, movidos, opps).
Saída:
  auditoria_<ini>_a_<fim>.md               scorecard + veredito + evidências + DIA ATUAL + lista uma a uma
  auditoria_<ini>_a_<fim>_classificada.json  cada atividade com tier + motivos (base da leitura humana)

A regex é o PRIMEIRO FILTRO. O Claude lê o texto integral das não-automáticas,
diretor por diretor, e corrige o tier quando a leitura contradiz a regra.
"""
import sys, json, re, statistics
from collections import defaultdict, Counter
from datetime import datetime, timedelta
from pathlib import Path

# ═══ detectores (auto herdado do reporte diário / calor-do-dia) ═══
AUTO_ANY = [r"mail\s*merge", r"this is an automatic activity", r"automatic activity generated",
            r"template using the", r"response generated by", r"created the .*template"]
AUTO_START = [r"^(please\s+)?begin work", r"^assigned", r"^management task", r"moved to stage",
              r"^opportunity .*(created|updated|reassigned)", r"^lead .*(created|qualified|disqualified)",
              r"^workflow", r"^reminder:", r"notifica[çc][ãa]o autom[áa]tica", r"^atividade gerada pelo sistema",
              r"^follow-?up: begin work"]
SISTEMA = re.compile(r"system|sistema|workflow|power automate|flow|apwreports|crm admin|integra", re.I)

SIN = [r"(r\$|\b\d{1,3}(\.\d{3})+(,\d{2})?\b)",
       r"\b(s[íi]ndic|propriet[áa]ri|administrador|condom[íi]ni|operadora|torre|locador|advogad|herdeir|procurador|dono|dona)",
       r"\b(pr[óo]xim[oa] passo|retorn|agend|envi|aguard|follow|reuni[ãa]o|visita|proposta|marc|lig)",
       r"\b(obje[çc]|recus|negocia|contraproposta|exig|condi[çc]|quer\b|pediu|preocupa|interess|aceit|assembl)"]
CONTRAPARTE = re.compile(SIN[1], re.I)
TENTATIVA = re.compile(r"n[ãa]o atend|caixa postal|sem retorno|deixei recado|recado|n[ãa]o respond|"
                       r"tentativa|tentei|n[úu]mero (errado|inexistente)|fora de [áa]rea|ocupad|"
                       r"desligad|n[ãa]o localizad|sem sucesso|chamou e", re.I)

def is_auto(a):
    t = f"{a.get('subject','')} {a.get('desc','')}".strip()
    if any(re.search(rx, t, re.I) for rx in AUTO_ANY): return True
    if any(re.search(rx, t[:90], re.I) for rx in AUTO_START): return True
    # criada pelo sistema E sem texto próprio
    return bool(SISTEMA.search(a.get("criada_por","")) and a.get("desc_len",0) < 40)

def n_sinais(t): return sum(1 for rx in SIN if re.search(rx, t, re.I))
def substantiva(t):
    L = len(t.strip()); return L >= 180 or (L >= 140 and n_sinais(t) >= 2)
def ts(s):
    try: return datetime.strptime(s, "%Y-%m-%d %H:%M:%S")
    except Exception: return None
def norm_txt(t):
    t = re.sub(r"\d+", "#", (t or "").lower()); t = re.sub(r"[^\w#]+", " ", t)
    return re.sub(r"\s+", " ", t).strip()

TIERS = [("REAL","🟢"),("TENTATIVA","🟡"),("RASA","🟠"),("SUSPEITA","🔴"),("AUTO","⚪")]
EMO = dict(TIERS)

def classifica(acts):
    por_dir = defaultdict(list)
    for a in acts: por_dir[a["owner"]].append(a)

    # rajada: ≥5 concluídas pelo mesmo diretor dentro de 10 min
    for lst in por_dir.values():
        lst.sort(key=lambda a: a.get("concluida",""))
        t = [ts(a.get("concluida","")) for a in lst]; j = 0
        for i in range(len(lst)):
            if t[i] is None: continue
            while t[j] is None or (t[i]-t[j]) > timedelta(minutes=10): j += 1
            if i-j+1 >= 5:
                for k in range(j, i+1): lst[k]["_rajada"] = True

    # copy-paste: mesmo texto (≥40 car.) do mesmo diretor em ≥3 registros distintos
    grupos = defaultdict(set)
    for a in acts:
        n = norm_txt(a.get("desc",""))
        if len(n) >= 40: grupos[(a["owner"], n)].add(a.get("reg_guid") or a["id"])
    dup = {k for k, v in grupos.items() if len(v) >= 3}

    # disparo: mesmo assunto em ≥10 e-mails do mesmo diretor
    subj = Counter((a["owner"], norm_txt(a.get("subject",""))) for a in acts if a.get("tipo")=="email")

    for a in acts:
        t = f"{a.get('subject','')} {a.get('desc','')}".strip()
        d = a.get("desc","") or ""; mot = []
        cri, con, pra = ts(a.get("criada","")), ts(a.get("concluida","")), ts(a.get("prazo",""))
        idade = (con - cri).days if cri and con else 0
        vencida = (con - pra).days if pra and con else 0
        rasa_txt = len(d.strip()) < 60
        a["idade_dias"] = idade; a["vencida_dias"] = max(vencida, 0)
        a["backlog"] = idade >= 7 or vencida > 3

        if is_auto(a) or (a.get("tipo")=="email" and subj[(a["owner"], norm_txt(a.get("subject","")))] >= 10):
            tier = "AUTO"; mot.append("automática/disparo em massa")
        else:
            if (a["owner"], norm_txt(d)) in dup: mot.append("texto idêntico em ≥3 registros")
            if a.get("_rajada") and rasa_txt: mot.append("fechada em rajada (≥5 em 10 min) sem texto")
            if a["backlog"] and rasa_txt: mot.append(f"velha fechada sem registro (criada há {idade}d, vencida {max(vencida,0)}d)")
            if not a.get("reg_guid") and rasa_txt: mot.append("sem vínculo e sem texto")
            if mot: tier = "SUSPEITA"
            elif substantiva(t) and (CONTRAPARTE.search(t) or n_sinais(t) >= 2):
                tier = "REAL"; mot.append(f"{len(d)} car., {n_sinais(t)} sinais")
            elif TENTATIVA.search(t): tier = "TENTATIVA"; mot.append("tentativa de contato")
            elif len(d.strip()) >= 80 and n_sinais(t) >= 2: tier = "REAL"; mot.append("curta mas com contraparte/próximo passo")
            elif len(d.strip()) >= 60: tier = "TENTATIVA"; mot.append("operacional, sem avanço claro")
            else: tier = "RASA"; mot.append("sem texto útil" if len(d.strip()) < 15 else "texto genérico")
            if a.get("_rajada") and tier != "SUSPEITA": mot.append("registrada em lote")
        a["tier"] = tier; a["motivos"] = mot
        a.pop("_rajada", None)
    return por_dir

def veredito(s, mediana):
    real, sus, tot = s["pct"]["REAL"], s["pct"]["SUSPEITA"], s["n_util"]
    if sus >= 20: return "🔴 Indício de maquiagem de CRM"
    if mediana and tot < 0.4*mediana: return "🟡 Volume baixo — confirmar se trabalha fora do CRM"
    if real >= 35 and sus < 10: return "✅ Trabalho real registrado"
    if tot >= mediana and real < 20: return "⚠️ Volume sem substância"
    return "🟡 Misto — ler evidências"

def cap(t, n): t = re.sub(r"\s+", " ", t or "").strip(); return t if len(t) <= n else t[:n].rsplit(" ",1)[0]+" […]"

def main():
    src, outdir = sys.argv[1], Path(sys.argv[2] if len(sys.argv) > 2 else ".")
    outdir.mkdir(parents=True, exist_ok=True)
    J = json.load(open(src))
    jan, acts, opps, mov = J["janela"], J["atividades"], J.get("opps", {}), J.get("movidos", [])
    dia = jan.get("dia_atual", jan["fim"])
    for a in acts:
        a.setdefault("hoje", a.get("concluida","")[:10] == dia)
        o = opps.get(a.get("reg_guid",""), {})
        a["L"] = o.get("L") or ("" if a.get("reg_tipo")=="opportunity" else (a.get("reg_tipo") or "sem vínculo"))
        a["deal"] = o.get("nome") or a.get("reg_nome","")
    por_dir = classifica(acts)

    mov_dir = defaultdict(list)
    for m in mov: mov_dir[m["dono"]].append(m)

    S = {}
    for d, lst in por_dir.items():
        c = Counter(a["tier"] for a in lst); util = [a for a in lst if a["tier"] != "AUTO"]
        nu = max(len(util), 1)
        horas = [ts(a["concluida"]) for a in util if ts(a.get("concluida",""))]
        dias = sorted({h.date() for h in horas})
        S[d] = {"n": len(lst), "n_util": len(util), "c": c,
                "pct": {k: round(100*c[k]/nu) for k, _ in TIERS if k != "AUTO"},
                "opps": len({a["reg_guid"] for a in util if a.get("reg_guid")}),
                "mov": Counter(m["tipo"] for m in mov_dir.get(d, [])),
                "dias_ativos": len(dias),
                "pos_19h": sum(1 for h in horas if h.hour >= 19),
                "fds": sum(1 for h in horas if h.weekday() >= 5),
                "hoje": [a for a in lst if a["hoje"]]}
    med = statistics.median([s["n_util"] for s in S.values()]) if S else 0
    for d in S: S[d]["veredito"] = veredito(S[d], med)

    ordem = sorted(S, key=lambda d: -S[d]["n_util"])
    L = [f"# Auditoria de atividades concluídas — {jan['ini']} → {jan['fim']}",
         f"Dia atual: **{dia}** · coletado {J.get('coletado_em','')[:16]}Z · {len(acts)} atividades · "
         f"{len(S)} diretor(es) · mediana úteis {med:.0f}", "",
         "> Regex é o 1º filtro. Leitura humana do texto é a palavra final. CRM mede REGISTRO, não trabalho.", "",
         "## Scorecard", "",
         "| Diretor | Úteis | 🟢 Real | 🟡 Tent. | 🟠 Rasa | 🔴 Susp. | ⚪ Auto | Opps | S1/S3/Rep | Dias | Hoje | Veredito |",
         "|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for d in ordem:
        s = S[d]; p = s["pct"]; mv = s["mov"]
        L.append(f"| {d} | {s['n_util']} | {p['REAL']}% | {p['TENTATIVA']}% | {p['RASA']}% | {p['SUSPEITA']}% | "
                 f"{s['c']['AUTO']} | {s['opps']} | {mv['S1']}/{mv['S3']}/{mv['REPROP']} | {s['dias_ativos']} | "
                 f"{len(s['hoje'])} | {s['veredito']} |")

    L += ["", f"## Concluídas no dia atual ({dia})", ""]
    for d in ordem:
        h = [a for a in S[d]["hoje"] if a["tier"] != "AUTO"]
        if not h: L.append(f"- **{d}** — nenhuma atividade útil concluída em {dia}"); continue
        c = Counter(a["tier"] for a in h); bk = sum(1 for a in h if a["backlog"])
        L.append(f"- **{d}** — {len(h)} úteis ({' · '.join(f'{EMO[k]} {c[k]}' for k,_ in TIERS if c[k])})"
                 + (f" · ⚠ {bk} eram backlog (velhas/vencidas fechadas hoje)" if bk else ""))

    for d in ordem:
        s, lst = S[d], por_dir[d]
        L += ["", f"## {d} — {s['veredito']}", "",
              f"{s['n']} concluídas ({s['c']['AUTO']} auto) · {s['opps']} opps · {s['dias_ativos']} dias com registro · "
              f"{s['pos_19h']} após 19h · {s['fds']} no fim de semana", ""]
        for tier, titulo, n in (("SUSPEITA","Suspeitas",6), ("REAL","Melhores registros",4)):
            ev = [a for a in lst if a["tier"] == tier]
            if tier == "REAL": ev.sort(key=lambda a: -a.get("desc_len",0))
            if ev:
                L.append(f"**{EMO[tier]} {titulo}**")
                for a in ev[:n]:
                    L.append(f"- `{a['concluida'][5:16]}` {a['L']} · {a['tipo_nome']} · {'; '.join(a['motivos'])} — "
                             f"_{cap(a.get('subject',''),60)}_ — {cap(a.get('desc',''),260) or '(sem texto)'}")
                L.append("")
        L += ["<details><summary>Lista uma a uma (não-automáticas)</summary>", ""]
        for a in sorted([a for a in lst if a["tier"] != "AUTO"], key=lambda a: a["concluida"]):
            L.append(f"- {EMO[a['tier']]} `{a['concluida'][5:16]}`{' **HOJE**' if a['hoje'] else ''} {a['L']} "
                     f"· {a['tipo_nome']} · _{cap(a.get('subject',''),60)}_ — {cap(a.get('desc',''),600) or '(sem texto)'}")
        L += ["", "</details>"]

    base = f"auditoria_{jan['ini']}_a_{jan['fim']}"
    (outdir/f"{base}.md").write_text("\n".join(L), encoding="utf-8")
    json.dump({"janela": jan, "scorecard": {d: {k: v for k, v in S[d].items() if k != "hoje"} for d in S},
               "atividades": acts}, open(outdir/f"{base}_classificada.json","w"), ensure_ascii=False, default=str)
    print(f"OK — {outdir/base}.md  ·  {len(acts)} atividades  ·  mediana úteis {med:.0f}")
    for d in ordem: print(f"  {d:22s} úteis {S[d]['n_util']:4d}  real {S[d]['pct']['REAL']:3d}%  susp {S[d]['pct']['SUSPEITA']:3d}%  hoje {len(S[d]['hoje']):3d}  {S[d]['veredito']}")

if __name__ == "__main__":
    main()
