#!/usr/bin/env python3
"""build_semana.py — Atividades da Semana por Diretor (APW · reporte interno de gestão)
Uso:
  python3 build_semana.py <atividades_semana.json> <opps_extras.json|-> <pasta_saida>

  - Se <opps_extras.json> = "-", ignora enriquecimento (opps extras aparecem
    como "opp guid=..." sem L/nome).

Gera:
  - PNG resumo (top 3 opps por diretor + painel geral, colável no e-mail)
  - PDF completo (todas as opps por diretor + texto integral das atividades)
  - 2 HTMLs de backup

Identidade: apw-brand (Navy #012B5E, Azul #1C75BB, Sage #91A5A4, Verde #009877,
Oliva #A7AF00, Vermelho #C0392B).
"""
import sys, json, os, re, html, datetime
from pathlib import Path

# ═══ paleta APW ═══
NAVY="#012B5E"; AZUL="#1C75BB"; SAGE="#91A5A4"; VERDE="#009877"; OLIVA="#A7AF00"
RED="#C0392B"; CINZA="#5D5D5D"; AMBAR="#E8A33D"; BG2="#f7fafc"; LINE="#dce4ec"

# ═══ detectores (mesma lógica do calor-do-dia — trocar aqui = trocar lá) ═══
AUTO_ANY   = [r"mail\s*merge", r"this is an automatic activity", r"automatic activity generated",
              r"template using the", r"response generated by", r"created the .*template"]
AUTO_START = [r"^\s*$", r"^(please\s+)?begin work", r"^assigned", r"^management task",
              r"moved to stage", r"^opportunity .*(created|updated|reassigned)",
              r"^lead .*(created|qualified|disqualified)", r"^workflow", r"^reminder:",
              r"notifica[çc][ãa]o autom[áa]tica", r"^atividade gerada pelo sistema",
              r"^follow-?up: begin work"]

def is_auto(t):
    t = (t or "").strip()
    if not t: return True
    if any(re.search(rx, t, re.I) for rx in AUTO_ANY): return True
    return any(re.search(rx, t[:90], re.I) for rx in AUTO_START)

SIN = [r"\b(r\$|\d{1,3}(\.\d{3})+(,\d{2})?)",
       r"\b(s[íi]ndico|propriet[áa]rio|administradora|condom[íi]nio|operadora|torre|locador|advogad)",
       r"\b(pr[óo]ximo passo|retornar|agendar|enviar|aguard|follow|reuni[ãa]o|visita|proposta|marcar|ligar)",
       r"\b(objec|objeç|recus|negociaç|contraproposta|exig|condiç|quer|pediu|preocupa)"]

def subst(t):
    if not t: return False
    L = len(t.strip())
    return L >= 180 or (L >= 140 and sum(1 for rx in SIN if re.search(rx, t, re.I)) >= 2)

CALOR = [(r"\bAGE\b.*(aprovad|ok)|aprovaç[ãa]o.*AGE", "AGE aprovada", 3),
         (r"\baceite\b|\bLOI\b|aceitou a proposta|aceitaram", "Aceite / LOI", 3),
         (r"docusign|assinatur|assinad|assinou", "Assinatura", 3),
         (r"contraproposta|contra-proposta", "Contraproposta", 2),
         (r"\bproposta\b.*(enviad|apresent|entregu)|enviei a proposta", "Proposta enviada", 2),
         (r"R\$\s?\d{1,3}(\.\d{3})+", "Valor cheio", 1),
         (r"edital|matr[íi]cula|conven[çc][ãa]o", "Edital / matrícula", 1),
         (r"desconto|majora[çc]|aumento do aluguel", "Desconto / majoração", 1),
         (r"s[íi]ndico.*(interess|gostou|favor)|propriet[áa]rio.*(interess|gostou)",
          "Contraparte interessada", 2)]

FLAGS = [(r"\bIHS\b|\bCSS\b|Centennial", "IHS", "🟡", "IHS/CSS só compra terreno — cessão/DRS não fecha"),
         (r"\bTBSA\b|Torres do Brasil", "TBSA", "", ""),
         (r"\bPTI\b|Phoenix|\bQMC\b", "PTI/Phoenix/QMC", "🟡", "Confirmar cláusula anti-agregador"),
         (r"veda[çc][ãa]o|anti-?cess[ãa]o|anti-?drs|exclusividade telecom",
          "Trava contratual", "🔴", "Vedação/exclusividade citada no texto")]
COND_RX = r"condom[íi]nio|edif[íi]cio|\bcond\.|residencial|\bed\b|tower"

# ═══ helpers ═══
def esc(t): return html.escape((t or "").strip())

def clean(t):
    t = (t or "")
    t = re.sub(r"<(script|style)[^>]*>.*?</\1>", " ", t, flags=re.S|re.I)
    t = re.sub(r"<br\s*/?>|</p>|</div>|</tr>", "  ", t, flags=re.I)
    t = re.sub(r"<[^>]{0,400}>", " ", t)
    t = html.unescape(t)
    t = re.sub(r"https?://[^\s]{60,}", " [link] ", t)
    t = re.sub(r"[\r\n\t]+", " ", t); t = re.sub(r"\s{2,}", " ", t)
    return t.strip()

CAP = 900   # cap por texto de atividade no HTML resumo
def cap(t, n=CAP):
    t = clean(t)
    return t if len(t) <= n else t[:n].rsplit(" ", 1)[0] + " […]"

def bandeiras(texto_agregado, nome_deal):
    hits = []
    t = (nome_deal or "") + " " + (texto_agregado or "")
    for rx, label, emoji, razao in FLAGS:
        if re.search(rx, t, re.I):
            hits.append((label, emoji or "🟡", razao or label))
    # TBSA em condomínio (heurística): TBSA + palavra de condomínio no texto
    if "TBSA" in [h[0] for h in hits] and re.search(COND_RX, t, re.I):
        hits.append(("TBSA-cond", "🔴", "TBSA em condomínio — cessão travada"))
    elif "TBSA" in [h[0] for h in hits]:
        hits.append(("TBSA-terreno", "🟡", "TBSA fora de condomínio — rotear via DRS"))
    return hits

def score_calor(texto_agregado):
    hits = []
    for rx, label, peso in CALOR:
        if re.search(rx, texto_agregado or "", re.I):
            hits.append((label, peso))
    return sum(p for _, p in hits), hits

# ═══ core ═══
def carrega(atv_path, opps_path):
    atv = json.load(open(atv_path))
    if opps_path == "-":
        opps = {}
    else:
        opps = json.load(open(opps_path))
        # normalizar chaves pra lowercase (o snippet já faz, mas garantir)
        opps = {(k or "").lower(): v for k, v in opps.items()}
    return atv, opps

def monta_por_diretor(atv, opps):
    """Retorna {dir_nome: {n_movidos, n_ativ, opps: [ {L, nome, tipos, movida, ativs_semana, ...} ] }}"""
    deals_by_opp = {d["opp"]: d for d in atv["deals"]}
    # retrocompat: aceita acts_semana (formato oficial) ou acts_dia (formato do apw-calor-do-dia)
    acts = atv.get("acts_semana") or atv.get("acts_dia") or []

    # 1) construir dicionário de opps consolidado (movidas + extras)
    #    para cada opp: L, nome, dono_atual, dono_guid, tipos, movida (bool)
    opp_info = {}
    for d in atv["deals"]:
        opp_info[d["opp"]] = {
            "L": d["L"], "nome": d["nome"], "dono_atual": d["dono_atual"],
            "dono_guid": d["dono_guid"], "tipos": list(d["tipos"]),
            "pool": d.get("pool", False), "movida": True,
            "historico_completo": d.get("atividades", [])
        }
    for guid, info in opps.items():
        if guid in opp_info: continue   # já veio como movida
        opp_info[guid] = {
            "L": info.get("L", "?"), "nome": info.get("nome", ""),
            "dono_atual": info.get("dono_atual", ""),
            "dono_guid": (info.get("dono_guid") or "").lower(),
            "tipos": [], "pool": False, "movida": False,
            "historico_completo": []
        }

    # 2) enriquecer com atividades da semana (por opp)
    for a in acts:
        oid = (a.get("opp") or "").lower()
        if not oid or oid not in opp_info: continue
        opp_info[oid].setdefault("ativs_semana", []).append(a)

    # 3) agrupar por diretor (nome do dono_atual)
    #    fallback: se não achar nome, usa "—" (opps sem enrichment)
    grupos = {}
    for oid, o in opp_info.items():
        # opps só com atividade — o dono é quem fez a atividade (owner do acts)
        # opps movidas — o dono é o dono_atual do deal
        if not o.get("ativs_semana"):
            continue    # sem atividade na semana → não entra (mesmo se moveu, sem ativ não interessa neste report)
        dono = o.get("dono_atual") or ""
        # se opp tem múltiplos "owners" nas atividades da semana, o principal é o dono_atual da opp
        # mas se dono_atual está vazio (extra sem enrich), usa o owner mais frequente das ativs
        if not dono:
            from collections import Counter
            owners = Counter(a["owner"] for a in o["ativs_semana"] if a.get("owner"))
            dono = owners.most_common(1)[0][0] if owners else "— sem dono —"
        grupos.setdefault(dono, {"n_movidos": 0, "n_ativ": 0, "opps": []})
        grupos[dono]["opps"].append(o)
        if o["movida"]: grupos[dono]["n_movidos"] += 1
        grupos[dono]["n_ativ"] += len(o["ativs_semana"])

    return grupos

def enriquece_opp(o):
    """Adiciona ao dict da opp: bandeiras, calor, ultima_ativ do dono, texto_agregado"""
    # texto agregado (não-auto) → usado por bandeiras e calor
    ativs = o.get("ativs_semana", []) + o.get("historico_completo", [])
    textos = [ (a.get("desc") or "") + " " + (a.get("subject") or "") for a in ativs
               if not is_auto((a.get("desc") or "") + " " + (a.get("subject") or "")) ]
    txt_agreg = " ".join(textos)[:20000]
    o["bandeiras"] = bandeiras(txt_agreg, o.get("nome", ""))
    o["calor_score"], o["calor_hits"] = score_calor(txt_agreg)
    # última atividade DO DONO ATUAL da semana (fallback: última atividade da semana em geral, marcada em vermelho)
    do_dono = [a for a in o.get("ativs_semana", [])
               if a.get("owner_guid") == o.get("dono_guid") and not is_auto((a.get("desc") or "") + " " + (a.get("subject") or ""))]
    if not do_dono:
        do_dono = [a for a in o.get("ativs_semana", [])
                   if not is_auto((a.get("desc") or "") + " " + (a.get("subject") or ""))]
    ultima = None
    if do_dono:
        ultima = sorted(do_dono, key=lambda a: a.get("data", ""), reverse=True)[0]
    o["ultima_ativ"] = ultima
    o["ultima_do_dono"] = bool(do_dono and ultima and ultima.get("owner_guid") == o.get("dono_guid"))
    return o

def html_head(title):
    return f'''<!doctype html><html><head><meta charset="utf-8"><title>{esc(title)}</title>
<style>
  body{{margin:0;padding:0;background:#fff;font-family:Arial,Helvetica,sans-serif;color:{NAVY};font-size:12px;line-height:1.4;}}
  .wrap{{max-width:960px;margin:0 auto;padding:0;}}
  h1{{font-size:20px;margin:14px 26px 6px;color:{NAVY};}}
  h2.dir{{font-size:14px;margin:22px 26px 2px;padding:8px 12px;background:{NAVY};color:#fff;border-radius:3px;}}
  .dirmeta{{margin:0 26px 8px;font-size:11.5px;color:{CINZA};font-weight:bold;}}
  .subhead{{margin:10px 26px 2px;font-size:11px;font-weight:bold;color:{AZUL};letter-spacing:.4px;}}
  table.opps{{width:calc(100% - 52px);margin:2px 26px;border-collapse:collapse;font-size:11px;}}
  table.opps td{{padding:6px 8px;border-bottom:1px solid #eef2f6;vertical-align:top;color:{NAVY};}}
  .lcell{{width:145px;white-space:nowrap;font-weight:bold;}}
  .lchip{{display:inline-block;font-size:9.5px;font-weight:bold;padding:1.5px 5px;border-radius:3px;color:#fff;margin-left:4px;}}
  .cS1{{background:{SAGE};}} .cS3{{background:{AZUL};}} .cREPROP{{background:{OLIVA};}} .cNONE{{background:#c8d0d8;color:#333;}}
  .flag{{font-size:11px;margin-right:4px;}}
  .calor{{display:inline-block;background:#fff2df;color:{AMBAR};font-size:10px;font-weight:bold;padding:1px 5px;border-radius:3px;margin-left:4px;}}
  .qtd{{font-size:10px;color:{CINZA};}}
  .autor{{font-size:9.5px;color:{CINZA};padding-top:2px;}}
  .autor.red{{color:{RED};font-weight:bold;}}
  .semativ{{font-size:10px;color:{RED};font-style:italic;}}
  .painel{{margin:8px 26px 12px;padding:8px 12px;background:{BG2};border-radius:3px;font-size:11.5px;color:{NAVY};}}
  .footer{{margin:16px 26px 22px;font-size:10.5px;color:{SAGE};line-height:1.5;border-top:1px solid {LINE};padding-top:8px;}}
  .brand{{background:{NAVY};color:#fff;padding:10px 26px;margin-bottom:8px;font-size:14px;}}
  .brand b{{color:#fff;}} .brand span{{float:right;font-size:12px;opacity:.85;}}
  .hist{{margin:4px 26px 12px;padding:6px 10px;background:#fbfcfe;border-left:3px solid {SAGE};font-size:10.5px;color:{NAVY};line-height:1.5;}}
  .hist .h{{font-weight:bold;color:{AZUL};margin-bottom:2px;font-size:10.5px;}}
  .hist .item{{margin-bottom:6px;}}
  .hist .meta{{color:{CINZA};font-size:9.5px;}}
</style></head><body><div class="wrap">'''

def html_foot(nota):
    return f'''<div class="footer">{nota}</div></div></body></html>'''

def chip_tipos(tipos):
    if not tipos: return '<span class="lchip cNONE">—</span>'
    return "".join(f'<span class="lchip c{t}">{t}</span>' for t in tipos)

def render_opp_row(o, mostrar_texto=True):
    L = esc(o.get("L", "?"))
    nome = esc(o.get("nome", "") or o.get("opp", "")[:8])
    flags_html = "".join(f'<span class="flag" title="{esc(r)}">{e}</span>' for _, e, r in o.get("bandeiras", []))
    calor_html = f'<span class="calor">🔥 {o["calor_score"]}</span>' if o.get("calor_score", 0) >= 3 else ""
    n_ativ = len(o.get("ativs_semana", []))
    ua = o.get("ultima_ativ")
    if ua:
        txt = cap(clean((ua.get("desc") or "") + " · " + (ua.get("subject") or "")))
        autor_cls = "" if o.get("ultima_do_dono") else "red"
        autor_lbl = "" if o.get("ultima_do_dono") else f'⚠ nota de {esc(ua.get("owner", "outro diretor"))} '
        situacao = f'''
          <div>{esc(txt) if mostrar_texto else ""}</div>
          <div class="autor {autor_cls}">{autor_lbl}— {esc(ua.get("owner", ""))} · {esc(ua.get("data", ""))}</div>
        '''
    else:
        situacao = '<div class="semativ">— sem atividade concluída válida do dono na semana —</div>'
    return f'''<tr>
      <td class="lcell">{L}{chip_tipos(o["tipos"])}<div class="qtd">{n_ativ} ativ · {esc(o.get("nome", "")[:32])}</div></td>
      <td>{flags_html}{calor_html} {situacao}</td>
    </tr>'''

def render_diretor(dir_nome, g, mostrar_texto=True, incluir_historico=False):
    # ordenar opps: movidas primeiro (S3>S1>REPROP), depois só-ativ por # ativs desc
    def key_movida(o):
        t = o["tipos"]
        return -(("S3" in t)*100 + ("S1" in t)*10 + ("REPROP" in t))
    movidas = sorted([o for o in g["opps"] if o["movida"]], key=lambda o: (key_movida(o), -len(o.get("ativs_semana", []))))
    so_ativ = sorted([o for o in g["opps"] if not o["movida"]], key=lambda o: -len(o.get("ativs_semana", [])))

    n_opps = len(g["opps"])
    parts = [f'<h2 class="dir">{esc(dir_nome)}</h2>',
             f'<div class="dirmeta">{g["n_movidos"]} deal(s) movido(s) · {g["n_ativ"]} atividade(s) concluída(s) · {n_opps} opp(s) trabalhada(s)</div>']
    if movidas:
        parts.append(f'<div class="subhead">▶ MOVERAM ESTÁGIO ({len(movidas)})</div>')
        parts.append('<table class="opps"><tbody>' + "".join(render_opp_row(o, mostrar_texto) for o in movidas) + '</tbody></table>')
    if so_ativ:
        parts.append(f'<div class="subhead">▶ SÓ ATIVIDADE — NÃO MOVERAM ({len(so_ativ)})</div>')
        parts.append('<table class="opps"><tbody>' + "".join(render_opp_row(o, mostrar_texto) for o in so_ativ) + '</tbody></table>')

    # PDF: histórico cronológico completo por diretor (todas as ativs de todas as opps)
    if incluir_historico:
        todas = []
        for o in movidas + so_ativ:
            for a in o.get("ativs_semana", []):
                todas.append((o, a))
        todas.sort(key=lambda x: x[1].get("data", ""))
        if todas:
            parts.append('<div class="subhead">📜 HISTÓRICO DA SEMANA (cronológico)</div>')
            hist = []
            for o, a in todas:
                if is_auto((a.get("desc") or "") + " " + (a.get("subject") or "")):
                    continue
                autor_red = "red" if a.get("owner_guid") != o.get("dono_guid") else ""
                hist.append(f'''<div class="item">
                  <div class="h">{esc(o["L"])} · {esc(o.get("nome", "")[:60])} — {esc(a.get("subject", "")[:80])}</div>
                  <div>{esc(cap(a.get("desc") or "", 2500))}</div>
                  <div class="meta {autor_red}">— {esc(a.get("owner", ""))} · {esc(a.get("data", ""))}</div>
                </div>''')
            parts.append(f'<div class="hist">{"".join(hist)}</div>')

    return "\n".join(parts)

def render_painel(atv, grupos):
    n_dir_ativos = len([g for g in grupos.values() if g["n_ativ"] > 0])
    n_opps_total = sum(len(g["opps"]) for g in grupos.values())
    n_movidos = sum(g["n_movidos"] for g in grupos.values())
    n_ativ = sum(g["n_ativ"] for g in grupos.values())
    n_bandeiras = sum(1 for g in grupos.values() for o in g["opps"] if o.get("bandeiras"))
    janela = atv["_meta"].get("janela_ini", atv["alvo"])
    alvo = atv["alvo"]
    corte = atv["_meta"].get("d1", "")[11:16]  # HH:MM UTC
    # aproximar BRT (-3h)
    try:
        hh, mm = int(corte[:2]), int(corte[3:5])
        hh_brt = (hh - 3) % 24
        corte_brt = f"{hh_brt:02d}:{mm:02d}"
    except: corte_brt = corte
    return f'''<div class="painel">
      <b>Semana {janela[8:10]}/{janela[5:7]} → {alvo[8:10]}/{alvo[5:7]}/{alvo[:4]}</b> (corte {corte_brt} BRT)
      · {n_dir_ativos} diretor(es) ativo(s) · {n_opps_total} opp(s) trabalhada(s)
      · {n_movidos} movida(s) de estágio · {n_ativ} atividade(s) concluída(s) · {n_bandeiras} opp(s) com bandeira
    </div>'''

def build_html(atv, grupos, resumo=True):
    janela = atv["_meta"].get("janela_ini", atv["alvo"])
    alvo = atv["alvo"]
    titulo = f"Atividades da Semana {janela[8:10]}/{janela[5:7]} → {alvo[8:10]}/{alvo[5:7]}/{alvo[:4]} — por Diretor"
    h = [html_head(titulo)]
    h.append(f'<div class="brand"><b>APW<span style="opacity:.7">Brasil</span></b> <span>Atividades da Semana — Reporte Interno de Gestão · Diretoria de Aquisições</span></div>')
    h.append(f'<h1>{esc(titulo)}</h1>')
    h.append(render_painel(atv, grupos))

    # ordenar diretores por # atividades desc
    ordem = sorted(grupos.items(), key=lambda kv: -kv[1]["n_ativ"])

    if resumo:
        # limitar cada diretor às top 5 opps (movidas + só-ativ) pra caber no PNG
        for nome, g in ordem:
            g_lim = dict(g)
            movidas = [o for o in g["opps"] if o["movida"]]
            so_ativ = [o for o in g["opps"] if not o["movida"]]
            so_ativ_top = sorted(so_ativ, key=lambda o: -len(o.get("ativs_semana", [])))[:5]
            g_lim["opps"] = movidas + so_ativ_top
            h.append(render_diretor(nome, g_lim, mostrar_texto=True, incluir_historico=False))
    else:
        for nome, g in ordem:
            h.append(render_diretor(nome, g, mostrar_texto=True, incluir_historico=True))

    nota = ("Deals movidos = S1/S3/Repropostas com data de estágio dentro da janela. Opps 'Só atividade' = "
            "opps que tiveram atividade concluída (statecode=1) na janela mas não mudaram de estágio. "
            "Bandeiras = heurística de texto sobre nome + descrições (confirmar detentora no CRM). "
            "Calor = score por sinais fortes (AGE, LOI, contraproposta, valor cheio). "
            "Última atividade = do DONO ATUAL; se em vermelho, é de outro diretor (histórico). "
            "Automáticas (Mail Merge, workflow, moved to stage) descartadas do conteúdo. "
            "<b>Uso interno — não circular fora da Diretoria de Aquisições.</b>")
    h.append(html_foot(nota))
    return "\n".join(h)

def main():
    if len(sys.argv) < 3:
        print("uso: build_semana.py <atividades.json> <opps_extras.json|-> [pasta_saida]")
        sys.exit(1)
    atv_path = sys.argv[1]
    opps_path = sys.argv[2]
    out = sys.argv[3] if len(sys.argv) > 3 else "."
    Path(out).mkdir(parents=True, exist_ok=True)

    atv, opps = carrega(atv_path, opps_path)
    grupos = monta_por_diretor(atv, opps)
    # enriquecer cada opp
    for g in grupos.values():
        g["opps"] = [enriquece_opp(o) for o in g["opps"]]

    janela = atv["_meta"].get("janela_ini", atv["alvo"])
    alvo = atv["alvo"]
    base = f"atividades-semana-apw-{janela}-a-{alvo}"

    html_r = build_html(atv, grupos, resumo=True)
    html_c = build_html(atv, grupos, resumo=False)
    fr = os.path.join(out, base + "-resumo.html")
    fc = os.path.join(out, base + "-completo.html")
    open(fr, "w").write(html_r)
    open(fc, "w").write(html_c)

    png = os.path.join(out, base + ".png")
    pdf = os.path.join(out, base + ".pdf")
    try:
        from playwright.sync_api import sync_playwright
        with sync_playwright() as p:
            b = p.chromium.launch(executable_path="/opt/google/chrome/chrome",
                                  args=["--no-sandbox", "--force-color-profile=srgb"])
            # PNG resumo (viewport 960 × altura variável, DSR 2 = retina)
            pg = b.new_page(viewport={"width": 960, "height": 800}, device_scale_factor=2)
            pg.goto("file://" + os.path.abspath(fr)); pg.wait_for_load_state("networkidle")
            pg.screenshot(path=png, full_page=True); pg.close()
            # PDF completo A4
            pg2 = b.new_page()
            pg2.goto("file://" + os.path.abspath(fc)); pg2.wait_for_load_state("networkidle")
            pg2.pdf(path=pdf, format="A4", print_background=True,
                    margin={"top": "9mm", "bottom": "9mm", "left": "6mm", "right": "6mm"})
            b.close()
        print("OK png(resumo):", png)
        print("OK pdf(completo):", pdf)
    except Exception as e:
        print("HTML ok, render falhou:", e)
        print("HTMLs:", fr, "|", fc)

if __name__ == "__main__":
    main()
